<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Kundli - {{ $kundli->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #4F46E5; padding-bottom: 20px; }
        .header h1 { color: #4F46E5; margin: 0; }
        .section { margin-bottom: 25px; }
        .section h2 { color: #4F46E5; border-bottom: 1px solid #E5E7EB; padding-bottom: 10px; }
        .info-grid { display: table; width: 100%; }
        .info-row { display: table-row; }
        .info-label { display: table-cell; font-weight: bold; padding: 8px; width: 40%; }
        .info-value { display: table-cell; padding: 8px; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #6B7280; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $kundli->name }}'s Kundli</h1>
        <p>{{ ucfirst($kundli->type) }} Birth Chart Analysis</p>
    </div>

    <div class="section">
        <h2>Birth Details</h2>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Full Name:</div>
                <div class="info-value">{{ $kundli->name }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Date of Birth:</div>
                <div class="info-value">{{ $kundli->birth_date->format('F d, Y') }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Time of Birth:</div>
                <div class="info-value">{{ $kundli->birth_time }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Place of Birth:</div>
                <div class="info-value">{{ $kundli->birth_place }}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Astrological Details</h2>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Rashi (Moon Sign):</div>
                <div class="info-value">{{ $kundli->rashi ?? 'To be calculated' }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Nakshatra:</div>
                <div class="info-value">{{ $kundli->nakshatra ?? 'To be calculated' }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Lagna (Ascendant):</div>
                <div class="info-value">{{ $kundli->lagna ?? 'To be calculated' }}</div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Kundli Information</h2>
        <div class="info-grid">
            <div class="info-row">
                <div class="info-label">Kundli Type:</div>
                <div class="info-value">{{ ucfirst($kundli->type) }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Generated On:</div>
                <div class="info-value">{{ $kundli->created_at->format('F d, Y') }}</div>
            </div>
            <div class="info-row">
                <div class="info-label">Status:</div>
                <div class="info-value">{{ ucfirst($kundli->status) }}</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This kundli was generated by AstroServices</p>
        <p>For consultation and detailed analysis, visit our website</p>
    </div>
</body>
</html>
